DRIVER_PATH = r"C:\Users\Hilmi\dev-projects\skripsi-selenium\chromedriver_win32\chromedriver.exe"
CHROME_PATH = r"C:\Users\Hilmi\dev-projects\skripsi-selenium\chrome-10905414120\chrome.exe"
CHROME_DATA = r"user-data-dir=C:\Users\Hilmi\AppData\Local\Chromium\User Data"
BASE_URL = "http://localhost:8000"
EMAIL = "admin@eecid.com"
PASSWORD = "secret"
NEW_PASSWORD = "secret1"
